In [6]:
import plotly.express as px
import pandas as pd
import numpy as np
import seaborn as sns
import plotly.io as pio
pio.renderers.default="notebook"

In [3]:
df=pd.read_csv("social_media_engagement.csv")

In [4]:
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [5]:
df.columns

Index(['post_id', 'platform', 'post_type', 'post_time', 'likes', 'comments',
       'shares', 'post_day', 'sentiment_score'],
      dtype='object')

In [26]:
fig=px.bar(data_frame=df,x="post_type",y="likes",text_auto=True,color="comments",color_discrete_map={"Facebook":"yellow","Instagram":"red","Twitter":"black"},height=700,width=2000,title="Platform",hover_data=["post_day","sentiment_score"],facet_col="sentiment_score",facet_row="post_day")
fig.show()

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [23]:
px.bar(data_frame=df,x="post_type",y=["likes","comments","shares"],color="platform",barmode="group",pattern_shape="sentiment_score",text="comments")

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [20]:
df.dtypes.unique()

array([dtype('int64'), dtype('O')], dtype=object)

In [25]:
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [37]:
px.scatter(data_frame=df,x="likes",y="comments",color_discrete_sequence=["blue","red","yellow"],size="shares",hover_data=["post_day"],facet_col="sentiment_score",facet_row="post_day")

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [40]:
px.scatter_3d(data_frame=df,height=1000,width=700,x="likes",y="comments",z="shares",color="platform")

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [41]:
df.columns

Index(['post_id', 'platform', 'post_type', 'post_time', 'likes', 'comments',
       'shares', 'post_day', 'sentiment_score'],
      dtype='object')

In [42]:
df

,post_id,platform,post_type,post_time,likes,comments,shares,post_day,sentiment_score
0,1,Facebook,image,8/17/2023 14:45,2121,474,628,Thursday,positive
1,2,Facebook,carousel,5/14/2023 0:45,3660,432,694,Sunday,neutral
2,3,Instagram,poll,2/21/2023 16:15,4955,408,688,Tuesday,negative
3,4,Twitter,image,11/16/2023 0:45,1183,90,187,Thursday,negative
4,5,Twitter,video,5/23/2023 0:30,3499,247,286,Tuesday,positive
...,...,...,...,...,...,...,...,...,...
95,96,Instagram,carousel,7/12/2023 17:45,36,294,911,Wednesday,positive
96,97,Twitter,video,10/27/2023 23:45,314,108,458,Friday,neutral
97,98,Twitter,text,8/5/2023 8:45,229,179,38,Saturday,positive
98,99,Instagram,poll,12/29/2023 12:15,5000,500,204,Friday,positive
99,100,Instagram,image,6/6/2023 21:00,4483,357,25,Tuesday,neutral

In [43]:
px.scatter_matrix(data_frame=df,dimensions=["likes","comments","shares"],color="platform",size="likes")

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [48]:
px.line(data_frame=df,x="post_id",y="likes",color="post_type",hover_data=["sentiment_score"],markers=True)

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [50]:
data=df.groupby("platform",as_index=False)[["likes","comments","shares"]].sum()

In [51]:
data

    platform   likes  comments  shares
0   Facebook   86392      7965   15180
1  Instagram  107994      8368   18906
2    Twitter   43795      3933    7479

In [53]:
fig=px.pie(data_frame=data,names="platform",values="likes")

In [54]:
fig

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [55]:
fig.update_traces(textinfo="percent+label",textposition="outside",pull=[0.2,0,0])

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(

In [56]:
dd=pd.DataFrame({"dep":["hr","it","hr","it","admin","hr","it"],"salary":[1000,500,700,800,900,1200,1500],"age":[20,25,30,35,22,32,45],"gender":["F","M","F","F","M","F","M"]})

In [57]:
dd

     dep  salary  age gender
0     hr    1000   20      F
1     it     500   25      M
2     hr     700   30      F
3     it     800   35      F
4  admin     900   22      M
5     hr    1200   32      F
6     it    1500   45      M

In [67]:
px.histogram(data_frame=dd,x="dep",y="salary",histfunc="count",color="gender")

C:\ProgramData\Anaconda3\lib\site-packages\plotly\io\_renderers.py:51: UserWarning: Plotly version >= 6 requires Jupyter Notebook >= 7 but you have 6.1.4 installed.
 To upgrade Jupyter Notebook, please run `pip install notebook --upgrade`.
  warnings.warn(