In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv("production_analysis_dataset.csv")
df.columns

Index(['production_id', 'product_category', 'factory', 'shift', 'supervisor',
       'units_produced', 'defective_units', 'production_time_hr',
       'machine_downtime_hr', 'energy_consumption_kwh', 'profit'],
      dtype='object')

# Q1. Find the total units produced by each product_category.

In [3]:
df.groupby("product_category")["units_produced"].sum()

product_category
Automotive     9408
Electronics    7491
Furniture      7251
Name: units_produced, dtype: int64

# Q2. Calculate the average profit for each factory.

In [4]:
df.groupby("factory")["profit"].mean()

factory
Plant_A    18044.375000
Plant_B    16973.384615
Plant_C    18086.076923
Name: profit, dtype: float64

# Q3. Find the total defective_units for each shift.

In [5]:
df.groupby("shift")['defective_units'].sum()

shift
Evening    132
Morning    472
Night      471
Name: defective_units, dtype: int64

# Q4. Calculate the average production_time_hr for each supervisor.

In [6]:
df.groupby('supervisor')['production_time_hr'].mean()

supervisor
S1    7.801818
S2    7.450000
S3    7.882000
S4    7.956154
Name: production_time_hr, dtype: float64

# Q5. Find the total energy_consumption_kwh for each factory and shift.

In [10]:
df.groupby(["factory","shift"])['energy_consumption_kwh'].sum()

factory  shift
Plant_A  Evening     3330
         Morning    11144
         Night      12913
Plant_B  Evening     2889
         Morning     7923
         Night       4981
Plant_C  Evening     2214
         Morning     5632
         Night       7363
Name: energy_consumption_kwh, dtype: int64

In [9]:
df.groupby("shift")['energy_consumption_kwh'].sum()

shift
Evening     8433
Morning    24699
Night      25257
Name: energy_consumption_kwh, dtype: int64

# Q6. For each product_category, calculate:
total units_produced
average profit
maximum defective_units.

In [11]:
df.groupby('product_category').agg({"units_produced":"sum","profit":"mean","defective_units":"max"})

                  units_produced        profit  defective_units
product_category
Automotive                  9408  18374.722222               34
Electronics                 7491  16945.750000               40
Furniture                   7251  17935.062500               39

# Q7. For each factory, calculate:
mean production_time_hr
median machine_downtime_hr.

In [13]:
df.groupby("factory").agg({"production_time_hr":"mean","machine_downtime_hr":"median"})

         production_time_hr  machine_downtime_hr
factory
Plant_A            7.890000                0.945
Plant_B            7.579231                1.070
Plant_C            7.810769                0.850

# Q8. For each shift, compute:
minimum profit
maximum profit
average units_produced.

In [15]:
df.groupby("shift").agg({"profit":["min","max"],"units_produced":"mean"})

        profit        units_produced
           min    max           mean
shift
Evening  10009  22302     524.857143
Morning  10722  24358     482.090909
Night    12045  24586     470.000000

# Q9. For each supervisor, calculate:
total units_produced
total defective_units.

In [16]:
df.groupby("supervisor").agg({"units_produced":"sum","defective_units":"sum"})

            units_produced  defective_units
supervisor
S1                    5231              209
S2                    6069              264
S3                    7418              273
S4                    5432              329

# Q10. Using apply(), calculate the defect rate for each row:
defect_rate=defective_units/units_produced

In [17]:
df["defect_rate"]=df.apply(lambda x:(x["defective_units"]/x["units_produced"]),axis=1)

In [18]:
df

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit,defect_rate
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286,0.019139
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279,0.053156
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261,0.058559
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674,0.046414
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045,0.044118
5,106,Electronics,Plant_B,Morning,S2,621,28,8.23,1.12,846,20834,0.045089
6,107,Furniture,Plant_B,Morning,S3,351,29,7.33,1.03,1173,12664,0.082621
7,108,Electronics,Plant_B,Evening,S3,659,9,8.33,0.42,1546,14010,0.013657
8,109,Electronics,Plant_A,Morning,S3,627,40,7.16,0.62,1586,22713,0.063796
9,110,Automotive,Plant_B,Morning,S4,505,22,6.70,1.39,1380,24358,0.043564
10,111,Automotive,Plant_B,Night,S4,502,34,6.93,0.38,1562,19197,0.067729
11,112,Furniture,Plant_A,Morning,S1,598,30,7.59,1.50,941,18348,0.050167
12,113,Furniture,Plant_C,Evening,S3,378,15,8.88,0.75,865,16304,0.039683
13,114,Furniture,Plant_C,Evening,S1,583,5,8.54,0.35,1349,22302,0.008576
14,115,Automotive,Plant_B,Night,S2,450,32,6.97,0.20,1539,24349,0.071111
15,116,Automotive,Plant_A,Morning,S3,559,11,9.11,0.59,1454,18317,0.019678
16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009,0.021739
17,118,Electronics,Plant_A,Night,S1,357,28,9.14,1.28,1114,13923,0.078431
18,119,Electronics,Plant_A,Night,S4,343,36,8.95,1.47,1345,22547,0.104956
19,120,Automotive,Plant_C,Night,S2,581,15,7.30,1.33,1233,13470,0.025818
20,121,Automotive,Plant_B,Morning,S2,665,24,7.70,1.07,1182,17177,0.036090
21,122,Electronics,Plant_A,Morning,S1,415,9,7.51,0.96,1035,19641,0.021687
22,123,Electronics,Plant_B,Night,S4,417,9,9.22,1.32,872,18423,0.021583
23,124,Furniture,Plant_A,Evening,S4,409,39,6.90,1.42,1384,19440,0.095355
24,125,Furniture,Plant_C,Morning,S1,397,11,6.79,0.76,1233,16735,0.027708
25,126,Electronics,Plant_A,Night,S4,331,30,8.68,1.24,911,14073,0.090634
26,127,Automotive,Plant_A,Morning,S1,371,32,7.05,0.80,877,17260,0.086253
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166,0.057637
28,129,Furniture,Plant_C,Night,S4,301,29,7.30,1.22,1265,14673,0.096346
29,130,Automotive,Plant_A,Night,S3,379,17,7.39,1.46,1393,22054,0.044855
30,131,Electronics,Plant_C,Morning,S2,329,8,8.25,0.85,1343,12579,0.024316
31,132,Automotive,Plant_A,Night,S1,335,9,8.53,0.51,922,24586,0.026866
32,133,Furniture,Plant_A,Night,S3,617,10,7.76,0.96,1335,15183,0.016207
33,134,Furniture,Plant_A,Morning,S4,422,21,7.69,1.07,1107,17491,0.049763
34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170,0.017799
35,136,Automotive,Plant_C,Morning,S3,445,15,7.81,0.91,1109,20021,0.033708
36,137,Electronics,Plant_C,Night,S2,639,11,9.32,0.37,918,24577,0.017214
37,138,Automotive,Plant_B,Night,S4,439,23,8.31,1.13,1008,21263,0.052392
38,139,Electronics,Plant_B,Morning,S3,428,8,6.78,0.75,1083,10722,0.018692
39,140,Electronics,Plant_C,Morning,S1,382,33,8.16,0.76,809,11832,0.086387
40,141,Electronics,Plant_B,Morning,S2,489,40,6.94,0.37,1115,15974,0.081800
41,142,Automotive,Plant_A,Morning,S2,641,11,7.56,0.93,1216,20168,0.017161
42,143,Furniture,Plant_C,Night,S2,390,31,6.57,1.16,1140,22818,0.079487
43,144,Furniture,Plant_A,Morning,S4,436,15,8.86,0.34,839,24067,0.034404
44,145,Automotive,Plant_A,Evening,S3,479,24,8.96,1.33,1028,10387,0.050104
45,146,Furniture,Plant_C,Night,S3,442,9,9.40,0.56,1456,18346,0.020362
46,147,Electronics,Plant_A,Night,S4,314,12,9.13,0.54,1394,14349,0.038217
47,148,Automotive,Plant_A,Evening,S1,476,25,7.81,1.48,918,16311,0.052521
48,149,Automotive,Plant_C,Night,S2,662,32,6.51,1.40,1351,21253,0.048338
49,150,Furniture,Plant_C,Morning,S3,486,32,6.71,1.06,1138,20209,0.065844

# Q11. Using groupby().apply(), find the profit range (max − min) for each factory.

In [19]:
df.groupby("factory")["profit"].apply(lambda x:x.max()-x.min())

factory
Plant_A    14199
Plant_B    14349
Plant_C    12745
Name: profit, dtype: int64

# Q12. Using groupby().apply(), find the row with maximum units_produced in each product_category.

In [21]:
a=df.groupby("product_category",as_index=False).apply(lambda x:x[x["units_produced"]==x["units_produced"].max()]).reset_index()

In [22]:
a

,level_0,level_1,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit,defect_rate
0,0,16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009,0.021739
1,1,2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261,0.058559
2,2,34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170,0.017799

# Q13. Use apply() to create a new column efficiency_score:
efficiency=units_produced/production_time_hr

In [23]:
df["efficiency_score"]=df.apply(lambda x:x["units_produced"]/x["production_time_hr"],axis=1)

In [24]:
df

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit,defect_rate,efficiency_score
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286,0.019139,95.288754
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279,0.053156,91.212121
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261,0.058559,85.824742
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674,0.046414,68.005739
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045,0.044118,53.363229
5,106,Electronics,Plant_B,Morning,S2,621,28,8.23,1.12,846,20834,0.045089,75.455650
6,107,Furniture,Plant_B,Morning,S3,351,29,7.33,1.03,1173,12664,0.082621,47.885402
7,108,Electronics,Plant_B,Evening,S3,659,9,8.33,0.42,1546,14010,0.013657,79.111645
8,109,Electronics,Plant_A,Morning,S3,627,40,7.16,0.62,1586,22713,0.063796,87.569832
9,110,Automotive,Plant_B,Morning,S4,505,22,6.70,1.39,1380,24358,0.043564,75.373134
10,111,Automotive,Plant_B,Night,S4,502,34,6.93,0.38,1562,19197,0.067729,72.438672
11,112,Furniture,Plant_A,Morning,S1,598,30,7.59,1.50,941,18348,0.050167,78.787879
12,113,Furniture,Plant_C,Evening,S3,378,15,8.88,0.75,865,16304,0.039683,42.567568
13,114,Furniture,Plant_C,Evening,S1,583,5,8.54,0.35,1349,22302,0.008576,68.266979
14,115,Automotive,Plant_B,Night,S2,450,32,6.97,0.20,1539,24349,0.071111,64.562410
15,116,Automotive,Plant_A,Morning,S3,559,11,9.11,0.59,1454,18317,0.019678,61.361142
16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009,0.021739,84.975369
17,118,Electronics,Plant_A,Night,S1,357,28,9.14,1.28,1114,13923,0.078431,39.059081
18,119,Electronics,Plant_A,Night,S4,343,36,8.95,1.47,1345,22547,0.104956,38.324022
19,120,Automotive,Plant_C,Night,S2,581,15,7.30,1.33,1233,13470,0.025818,79.589041
20,121,Automotive,Plant_B,Morning,S2,665,24,7.70,1.07,1182,17177,0.036090,86.363636
21,122,Electronics,Plant_A,Morning,S1,415,9,7.51,0.96,1035,19641,0.021687,55.259654
22,123,Electronics,Plant_B,Night,S4,417,9,9.22,1.32,872,18423,0.021583,45.227766
23,124,Furniture,Plant_A,Evening,S4,409,39,6.90,1.42,1384,19440,0.095355,59.275362
24,125,Furniture,Plant_C,Morning,S1,397,11,6.79,0.76,1233,16735,0.027708,58.468336
25,126,Electronics,Plant_A,Night,S4,331,30,8.68,1.24,911,14073,0.090634,38.133641
26,127,Automotive,Plant_A,Morning,S1,371,32,7.05,0.80,877,17260,0.086253,52.624113
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166,0.057637,49.571429
28,129,Furniture,Plant_C,Night,S4,301,29,7.30,1.22,1265,14673,0.096346,41.232877
29,130,Automotive,Plant_A,Night,S3,379,17,7.39,1.46,1393,22054,0.044855,51.285521
30,131,Electronics,Plant_C,Morning,S2,329,8,8.25,0.85,1343,12579,0.024316,39.878788
31,132,Automotive,Plant_A,Night,S1,335,9,8.53,0.51,922,24586,0.026866,39.273154
32,133,Furniture,Plant_A,Night,S3,617,10,7.76,0.96,1335,15183,0.016207,79.510309
33,134,Furniture,Plant_A,Morning,S4,422,21,7.69,1.07,1107,17491,0.049763,54.876463
34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170,0.017799,91.964286
35,136,Automotive,Plant_C,Morning,S3,445,15,7.81,0.91,1109,20021,0.033708,56.978233
36,137,Electronics,Plant_C,Night,S2,639,11,9.32,0.37,918,24577,0.017214,68.562232
37,138,Automotive,Plant_B,Night,S4,439,23,8.31,1.13,1008,21263,0.052392,52.827918
38,139,Electronics,Plant_B,Morning,S3,428,8,6.78,0.75,1083,10722,0.018692,63.126844
39,140,Electronics,Plant_C,Morning,S1,382,33,8.16,0.76,809,11832,0.086387,46.813725
40,141,Electronics,Plant_B,Morning,S2,489,40,6.94,0.37,1115,15974,0.081800,70.461095
41,142,Automotive,Plant_A,Morning,S2,641,11,7.56,0.93,1216,20168,0.017161,84.788360
42,143,Furniture,Plant_C,Night,S2,390,31,6.57,1.16,1140,22818,0.079487,59.360731
43,144,Furniture,Plant_A,Morning,S4,436,15,8.86,0.34,839,24067,0.034404,49.209932
44,145,Automotive,Plant_A,Evening,S3,479,24,8.96,1.33,1028,10387,0.050104,53.459821
45,146,Furniture,Plant_C,Night,S3,442,9,9.40,0.56,1456,18346,0.020362,47.021277
46,147,Electronics,Plant_A,Night,S4,314,12,9.13,0.54,1394,14349,0.038217,34.392114
47,148,Automotive,Plant_A,Evening,S1,476,25,7.81,1.48,918,16311,0.052521,60.947503
48,149,Automotive,Plant_C,Night,S2,662,32,6.51,1.40,1351,21253,0.048338,101.689708
49,150,Furniture,Plant_C,Morning,S3,486,32,6.71,1.06,1138,20209,0.065844,72.429210

# Q14. Find how many times each product_category appears in the dataset.

In [26]:
df.product_category.value_counts()

Automotive     18
Electronics    16
Furniture      16
Name: product_category, dtype: int64

# Q15. Count the number of records for each shift.

In [27]:
df["shift"].value_counts()

Morning    22
Night      21
Evening     7
Name: shift, dtype: int64

# Q16. Find the most frequent supervisor using value_counts().

In [29]:
df.supervisor.value_counts().head(1)

S3    15
Name: supervisor, dtype: int64

# Q17. Sort the dataset by profit in descending order.

In [30]:
df["profit"].sort_values(ascending=False)

31    24586
36    24577
9     24358
14    24349
27    24166
43    24067
2     23261
42    22818
8     22713
18    22547
13    22302
29    22054
37    21263
48    21253
5     20834
49    20209
41    20168
35    20021
21    19641
23    19440
10    19197
22    18423
11    18348
45    18346
15    18317
1     18279
33    17491
26    17260
20    17177
24    16735
47    16311
12    16304
40    15974
32    15183
28    14673
46    14349
25    14073
7     14010
17    13923
19    13470
6     12664
30    12579
0     12286
34    12170
4     12045
39    11832
3     11674
38    10722
44    10387
16    10009
Name: profit, dtype: int64

# Q18. Sort the dataset by:
•	product_category ascending
•	units_produced descending

In [33]:
df.sort_values(["product_category","units_produced"],ascending=[True,False])

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit,defect_rate,efficiency_score
16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009,0.021739,84.975369
20,121,Automotive,Plant_B,Morning,S2,665,24,7.70,1.07,1182,17177,0.036090,86.363636
48,149,Automotive,Plant_C,Night,S2,662,32,6.51,1.40,1351,21253,0.048338,101.689708
41,142,Automotive,Plant_A,Morning,S2,641,11,7.56,0.93,1216,20168,0.017161,84.788360
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286,0.019139,95.288754
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279,0.053156,91.212121
19,120,Automotive,Plant_C,Night,S2,581,15,7.30,1.33,1233,13470,0.025818,79.589041
15,116,Automotive,Plant_A,Morning,S3,559,11,9.11,0.59,1454,18317,0.019678,61.361142
9,110,Automotive,Plant_B,Morning,S4,505,22,6.70,1.39,1380,24358,0.043564,75.373134
10,111,Automotive,Plant_B,Night,S4,502,34,6.93,0.38,1562,19197,0.067729,72.438672
44,145,Automotive,Plant_A,Evening,S3,479,24,8.96,1.33,1028,10387,0.050104,53.459821
47,148,Automotive,Plant_A,Evening,S1,476,25,7.81,1.48,918,16311,0.052521,60.947503
14,115,Automotive,Plant_B,Night,S2,450,32,6.97,0.20,1539,24349,0.071111,64.562410
35,136,Automotive,Plant_C,Morning,S3,445,15,7.81,0.91,1109,20021,0.033708,56.978233
37,138,Automotive,Plant_B,Night,S4,439,23,8.31,1.13,1008,21263,0.052392,52.827918
29,130,Automotive,Plant_A,Night,S3,379,17,7.39,1.46,1393,22054,0.044855,51.285521
26,127,Automotive,Plant_A,Morning,S1,371,32,7.05,0.80,877,17260,0.086253,52.624113
31,132,Automotive,Plant_A,Night,S1,335,9,8.53,0.51,922,24586,0.026866,39.273154
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261,0.058559,85.824742
7,108,Electronics,Plant_B,Evening,S3,659,9,8.33,0.42,1546,14010,0.013657,79.111645
36,137,Electronics,Plant_C,Night,S2,639,11,9.32,0.37,918,24577,0.017214,68.562232
8,109,Electronics,Plant_A,Morning,S3,627,40,7.16,0.62,1586,22713,0.063796,87.569832
5,106,Electronics,Plant_B,Morning,S2,621,28,8.23,1.12,846,20834,0.045089,75.455650
40,141,Electronics,Plant_B,Morning,S2,489,40,6.94,0.37,1115,15974,0.081800,70.461095
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674,0.046414,68.005739
38,139,Electronics,Plant_B,Morning,S3,428,8,6.78,0.75,1083,10722,0.018692,63.126844
22,123,Electronics,Plant_B,Night,S4,417,9,9.22,1.32,872,18423,0.021583,45.227766
21,122,Electronics,Plant_A,Morning,S1,415,9,7.51,0.96,1035,19641,0.021687,55.259654
39,140,Electronics,Plant_C,Morning,S1,382,33,8.16,0.76,809,11832,0.086387,46.813725
17,118,Electronics,Plant_A,Night,S1,357,28,9.14,1.28,1114,13923,0.078431,39.059081
18,119,Electronics,Plant_A,Night,S4,343,36,8.95,1.47,1345,22547,0.104956,38.324022
25,126,Electronics,Plant_A,Night,S4,331,30,8.68,1.24,911,14073,0.090634,38.133641
30,131,Electronics,Plant_C,Morning,S2,329,8,8.25,0.85,1343,12579,0.024316,39.878788
46,147,Electronics,Plant_A,Night,S4,314,12,9.13,0.54,1394,14349,0.038217,34.392114
34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170,0.017799,91.964286
32,133,Furniture,Plant_A,Night,S3,617,10,7.76,0.96,1335,15183,0.016207,79.510309
11,112,Furniture,Plant_A,Morning,S1,598,30,7.59,1.50,941,18348,0.050167,78.787879
13,114,Furniture,Plant_C,Evening,S1,583,5,8.54,0.35,1349,22302,0.008576,68.266979
49,150,Furniture,Plant_C,Morning,S3,486,32,6.71,1.06,1138,20209,0.065844,72.429210
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045,0.044118,53.363229
45,146,Furniture,Plant_C,Night,S3,442,9,9.40,0.56,1456,18346,0.020362,47.021277
43,144,Furniture,Plant_A,Morning,S4,436,15,8.86,0.34,839,24067,0.034404,49.209932
33,134,Furniture,Plant_A,Morning,S4,422,21,7.69,1.07,1107,17491,0.049763,54.876463
23,124,Furniture,Plant_A,Evening,S4,409,39,6.90,1.42,1384,19440,0.095355,59.275362
24,125,Furniture,Plant_C,Morning,S1,397,11,6.79,0.76,1233,16735,0.027708,58.468336
42,143,Furniture,Plant_C,Night,S2,390,31,6.57,1.16,1140,22818,0.079487,59.360731
12,113,Furniture,Plant_C,Evening,S3,378,15,8.88,0.75,865,16304,0.039683,42.567568
6,107,Furniture,Plant_B,Morning,S3,351,29,7.33,1.03,1173,12664,0.082621,47.885402
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166,0.057637,49.571429
28,129,Furniture,Plant_C,Night,S4,301,29,7.30,1.22,1265,14673,0.096346,41.232877

In [34]:
dd=pd.read_csv("IPL_Matches_2008_2022.csv")

In [35]:
dd

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [36]:
dd.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='object')

In [55]:
dd.groupby("Season")["WinningTeam"].apply(lambda x:x.value_counts().head(1))

Season
2007/08  Rajasthan Royals         13
2009     Delhi Daredevils         10
2009/10  Mumbai Indians           11
2011     Chennai Super Kings      11
2012     Kolkata Knight Riders    12
2013     Mumbai Indians           13
2014     Kings XI Punjab          12
2015     Mumbai Indians           10
2016     Sunrisers Hyderabad      11
2017     Mumbai Indians           12
2018     Chennai Super Kings      11
2019     Mumbai Indians           11
2020/21  Mumbai Indians           11
2021     Chennai Super Kings      11
2022     Gujarat Titans           12
Name: WinningTeam, dtype: int64

In [40]:
dd.groupby("WinningTeam")["Player_of_Match"].nunique()

WinningTeam
Chennai Super Kings            39
Deccan Chargers                19
Delhi Capitals                 16
Delhi Daredevils               39
Gujarat Lions                   7
Gujarat Titans                  9
Kings XI Punjab                42
Kochi Tuskers Kerala            4
Kolkata Knight Riders          44
Lucknow Super Giants            6
Mumbai Indians                 43
Pune Warriors                  11
Punjab Kings                   10
Rajasthan Royals               41
Rising Pune Supergiant          7
Rising Pune Supergiants         3
Royal Challengers Bangalore    36
Sunrisers Hyderabad            36
Name: Player_of_Match, dtype: int64

In [44]:
dd.Venue.value_counts().head

Eden Gardens                                            77
Wankhede Stadium                                        73
M Chinnaswamy Stadium                                   65
Feroz Shah Kotla                                        60
Rajiv Gandhi International Stadium, Uppal               49
MA Chidambaram Stadium, Chepauk                         48
Sawai Mansingh Stadium                                  47
Dubai International Cricket Stadium                     46
Punjab Cricket Association Stadium, Mohali              35
Wankhede Stadium, Mumbai                                31
Sheikh Zayed Stadium                                    29
Sharjah Cricket Stadium                                 28
Maharashtra Cricket Association Stadium                 22
Dr DY Patil Sports Academy, Mumbai                      20
Dr DY Patil Sports Academy                              17
Brabourne Stadium, Mumbai                               17
Subrata Roy Sahara Stadium                              16
Rajiv Gandhi International Stadium                      15
Kingsmead                                               15
M.Chinnaswamy Stadium                                   15
Arun Jaitley Stadium                                    14
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium     13
Maharashtra Cricket Association Stadium, Pune           13
SuperSport Park                                         12
Sardar Patel Stadium, Motera                            12
Punjab Cricket Association IS Bindra Stadium, Mohali    11
Punjab Cricket Association IS Bindra Stadium            10
MA Chidambaram Stadium, Chepauk, Chennai                10
Saurashtra Cricket Association Stadium                  10
Brabourne Stadium                                       10
Holkar Cricket Stadium                                   9
MA Chidambaram Stadium                                   9
Himachal Pradesh Cricket Association Stadium             9
New Wanderers Stadium                                    8
Zayed Cricket Stadium, Abu Dhabi                         8
St George's Park                                         7
Narendra Modi Stadium, Ahmedabad                         7
Barabati Stadium                                         7
JSCA International Stadium Complex                       7
Newlands                                                 7
Shaheed Veer Narayan Singh International Stadium         6
Nehru Stadium                                            5
Green Park                                               4
Arun Jaitley Stadium, Delhi                              4
Vidarbha Cricket Association Stadium, Jamtha             3
De Beers Diamond Oval                                    3
Buffalo Park                                             3
Eden Gardens, Kolkata                                    2
OUTsurance Oval                                          2
Name: Venue, dtype: int64

In [45]:
new=pd.DataFrame()

In [46]:
new["count"]=dd.Venue.value_counts().head()

In [48]:
new.reset_index()

                                       index  count
0                               Eden Gardens     77
1                           Wankhede Stadium     73
2                      M Chinnaswamy Stadium     65
3                           Feroz Shah Kotla     60
4  Rajiv Gandhi International Stadium, Uppal     49

In [53]:
df1=new.merge(dd,on="Venue",how="inner",right_on="Venue")

MergeError: Can only pass argument "on" OR "left_on" and "right_on", not a combination of both.